name: Deploy to Vercel Staging

on:
  push:
    branches:
      - staging
  pull_request:
    branches:
      - staging

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger Vercel Deployment
        run: |
          echo "🚀 Triggering Vercel deploy for staging..."
          curl -X POST ${{ secrets.VERCEL_DEPLOY_HOOK_STAGING }}
